# Generated by Django 3.0.6 on 2020-05-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_video',
            field=models.CharField(default='NULL', max_length=1500),
        ),
    ]
